#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
for i in $(find . -name install.sh | sort); do
  sh -c $i
done
#find . -name install.sh | while read installer ; do echo $installer; sh -c "${installer}" ; done
